site_configs: &site_configs
  navbar_brand_html: >
    <a href="/" class="navbar-brand">Dipiy</a>
  navbar_html: >
    <li><a href="/topics/new">Posting</a>
  wiki_index_html: >
    <div>Wiki Home page.</div>
  wiki_sidebar_html: >
    <strong>Recommended content</strong>
    <ul>
      <li><a href="/wiki/about">about us</a></li>
    </ul>
  footer_html: >
    <p class="copyright">
     &copy; Powered by <a href="http://gethomeland.com"></a>.
    </p>
  after_topic_html: ""
  before_topic_html: ""
  topic_index_sidebar_html: ""
  site_index_html: "The following lists the relevant sites. If you know there are not in this list, please help add."
  custom_head_html: >
    <link rel="dns-prefetch" href="//assets.your-host.com">
  node_ids_hide_in_topics_index: ""
  new_topic_dropdown_node_ids: ""
  ban_words_on_reply: >
   mark
    Collection
    top
    Thumbs up
    up
  tips: >
     Tips 1
    Tip 2
  newbie_notices: >
    <p>To improve the quality of the community, to prevent new people to post a question, the new users need to meet the following conditions to post:</p>
    <ol style="color:#ad2b2d;">
      <li>Registration time more than one month;</li>
      <li>The number of replies must reach more than 10 posts;</li>
    </ol>
    <p>Please visit the new stage to see how other old users share and solve problems in the community.</p>
  reject_newbie_reply_in_the_evening: false
  apns_pem: ""
  blacklist_ips: ""
  newbie_limit_time:0

defaults: &defaults
  <<: *site_configs
  app_name: "<%= ENV['app_name'] %>"
  modules: "<%= ENV['modules'] || 'all'  %>"
  profile_fields: "<%= ENV['profile_fields'] || 'all' %>"
  domain: "<%= ENV['domain'] %>"
  https: <%= ENV['https'] || 'true' %>
  default_locale: "<%= ENV['default_locale'] || 'zh-CN' %>"
  auto_locale: <%= ENV['auto_locale'] || 'false' %>
  admin_emails: <%= ENV['admin_emails'] %>
  google_analytics_key: "<%= ENV['google_analytics_key'] %>"
  asset_host: "<%= ENV['asset_host'] %>"
  <% if ENV['rack_attack.limit'] == 'true' %>
  rack_attack:
    limit: <%= ENV['rack_attack.limit'] %>
    period: <%= ENV['rack_attack.period'] %>
  <% end %>
  upload_provider: "<%= ENV['upload_provider'] %>" # can be  upyun/aliyun
  upload_access_id: "<%= ENV['upload_access_id'] %>" # or username
  upload_access_secret: "<%= ENV['upload_access_secret'] %>" # or upyun password
  upload_bucket: "<%= ENV['upload_bucket'] %>"
  upload_url: "<%= ENV['upload_url'] %>"
  upload_aliyun_internal: <%= ENV['upload_aliyun_internal'] == 'true' %>
  upload_aliyun_area: "<%= ENV['upload_aliyun_area'] %>"
  mailer_provider: "<%= ENV['mailer_provider'] %>"
  mailer_sender: "<%= ENV['mailer_sender'] %>"
  mailer_options:
    <% if ENV['mailer_provider'] == 'postmark' %>
    api_key: '<%= ENV['mailer_options.api_key'] %>'
    <% else %>
    address: '<%= ENV['mailer_options.address'] %>'
    port: <%= ENV['mailer_options.port'] %>
    domain: '<%= ENV['mailer_options.domain'] %>'
    user_name: '<%= ENV['mailer_options.user_name'] %>'
    password: '<%= ENV['mailer_options.password'] %>'
    authentication: '<%= ENV['mailer_options.authentication'] %>'
    enable_starttls_auto: <%= ENV['mailer_options.enable_starttls_auto'] %>
    <% end %>
  sso:
    <% if ENV['sso.enable_provider'] != 'true' %>
    enable: <%= ENV['sso.enable'] || false %>
    <% else %>
    enable_provider: <%= ENV['sso.enable_provider'] || false %>
    <% end %>
    url: '<%= ENV['sso.url'] %>'
    secret: '<%= ENV['sso.secret'] %>'
  github_token: "<%= ENV['github_token'] %>"
  github_secret: "<%= ENV['github_secret'] %>"

production:
  <<: *defaults
